### ISSUE TITLE
Consider phasing out php 5.6, 7.0, 7.1, 7.2

### ISSUE THREAD

**Issue by 8ctopus** [deniskoronets/php-array-table#13]
This way the code can be strict typed.

**Comment by deniskoronets** [comment]
nope. it should be compatible with older version so people can integrate it in old projects. personally I have 7.2 at my job so...

**Comment by 8ctopus** [comment]
what about 5.6? People still on 5.6 can use 2.0.0 but not say 2.1.0

**Comment by 8ctopus** [comment]
Did you change your mind on this or should I close the issue?
