### ISSUE TITLE
Use colors

### ISSUE THREAD

**Issue by Sidha2** [deniskoronets/php-array-table#2]
How can I use colors with this class? There is some problem with escapes and explode I think

https://github.com/box/bart/blob/master/src/Bart/EscapeColors.php

**Comment by deniskoronets** [comment]
In case you can do the integration & tests - please raise a PR. Unfortunately I don't have much time to integrate it

**Comment by deniskoronets** [comment]
I just added color support in v2, check out here:
https://packagist.org/packages/dekor/php-array-table
