### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by 8ctopus** [deniskoronets/php-array-table#3]
First of all thank you for a great package!

One useful feature would be to be able to set the columns format. Here's an example:

```txt
+---------+-------+-------+---------+
| date    | total | count | average |
+---------+-------+-------+---------+
| 2022-07 | 8     | 1     | 8       |
| 2021-12 | 30    | 1     | 30      |
| 2020-12 | 96    | 7     | 13.7    |
```

The average value does not stick to a strict number of decimals which is not ideal.

**Comment by deniskoronets** [comment]
Just added support of formatting and align for columns, check out here:
https://packagist.org/packages/dekor/php-array-table
