### ISSUE TITLE
table colspan

### ISSUE THREAD

**Issue by alexmax220** [deniskoronets/php-array-table#6]
hi, thx for your project!

Can i use colspan if i need to merge few columns?
i need to make a "separator" in my table

**Comment by deniskoronets** [comment]
unfortunately I don't see a quick way to implement it within current architecture. There's anyway a workaround - you can register your own formatter so it calculates middle in column and splits it with using "|" char. See similar in AlignFormatter. In case you'll have it working well - raise a PR adding it into core formatters.
